version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "JokeMaestro1730897"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-52p1fmyrpuho"
s3_prefix = "JokeMaestro1730897"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
